# CONSTRAINT TRAPEZI
ALTER TABLE TRAPEZI ADD CONSTRAINT yptrno_1 FOREIGN KEY (yptrno) REFERENCES YPALLHLOS (ypan) ON DELETE CASCADE ON UPDATE CASCADE;
# CONSTRAINT PIATO
ALTER TABLE PIATO ADD CONSTRAINT pypan_1 FOREIGN KEY (pypan) REFERENCES YPALLHLOS (ypan) ON DELETE CASCADE ON UPDATE CASCADE;



